server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skins_db
    username: skins_user
    password: skins_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 7e44666976d5fa
    password: --
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: minhachavesegura
  expiration: 3600000

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health

info:
  db-status: "OK"
  app-status: "OK"